import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../core/theme/app_theme_scope.dart';
import '../../core/theme/color_theme_builder.dart';
import '../models/component_library_group.dart';
import '../models/component_note.dart';
import '../models/component_page_meta_data.dart';
import '../models/pending_variant.dart';
import '../widgets/color_role_swatch_grid.dart';
import '../widgets/component_page_scaffold.dart';
import '../widgets/component_section.dart';
import '../widgets/kpi_button_styles.dart';
import '../widgets/kpi_text_field.dart';
import '../widgets/m3_color_picker.dart';

/// M3 Color — https://m3.material.io/styles/color/overview
class ColorThemeComponentPage extends StatefulWidget {
  const ColorThemeComponentPage({super.key});

  static const meta = ComponentPageMetaData(
    id: 'color_theme',
    title: 'Color theme',
    sortOrder: 1,
    group: ComponentLibraryGroup.theme,
    m3SpecUrl: 'https://m3.material.io/styles/color/overview',
    description:
        'Material 3 color roles generated from primary and secondary inputs. '
        'Use the builder in Part 2 to preview the full theme before applying it.',
  );

  @override
  State<ColorThemeComponentPage> createState() => _ColorThemeComponentPageState();
}

class _ColorThemeComponentPageState extends State<ColorThemeComponentPage> {
  Brightness _brightness = Brightness.light;
  bool _syncedFromTheme = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (!_syncedFromTheme) {
      _brightness = Theme.of(context).brightness;
      _syncedFromTheme = true;
    }
  }

  static const _notes = <ComponentNote>[
    ComponentNote(
      variant: 'Primary',
      m3Behavior: 'Key brand color for prominent components and actions.',
      ourImplementation:
          'User input — locked into ColorScheme.fromSeed as primary seed and role.',
      action: 'Use builder',
    ),
    ComponentNote(
      variant: 'Secondary',
      m3Behavior: 'Less prominent accent for supporting UI and chips.',
      ourImplementation:
          'User input — locked into generated scheme as secondary role.',
      action: 'Use builder',
    ),
    ComponentNote(
      variant: 'Tertiary / surface / error',
      m3Behavior: 'Derived roles complete the accessible M3 palette.',
      ourImplementation:
          'Auto-generated by Flutter Material dynamic color (fidelity variant).',
      action: 'Use as-is',
    ),
    ComponentNote(
      variant: 'Light / dark',
      m3Behavior: 'Separate tonal mappings per brightness.',
      ourImplementation: 'Builder preview toggles Brightness.light and .dark.',
      action: 'Use builder',
    ),
  ];

  static const _pending = <PendingVariant>[
    PendingVariant(
      name: 'Custom tertiary input',
      foundIn: 'Advanced brand palettes',
      description: 'Optional third accent color — not in the two-input builder.',
      suggestedAction: 'Extend builder when needed',
    ),
    PendingVariant(
      name: 'Contrast level slider',
      foundIn: 'M3 dynamic scheme API',
      description: 'ColorScheme.fromSeed contrastLevel for accessibility tuning.',
      suggestedAction: 'Add to builder controls',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final theme = AppThemeScope.of(context);
    final primary = theme.primary;
    final secondary = theme.secondary;
    final snippet = ColorThemeBuilder.toDartSnippet(
      primary: primary,
      secondary: secondary,
      brightness: _brightness,
    );

    final scheme = ColorThemeBuilder.build(
      primary: primary,
      secondary: secondary,
      brightness: _brightness,
    );

    return ComponentPageScaffold(
      title: ColorThemeComponentPage.meta.title,
      m3SpecUrl: ColorThemeComponentPage.meta.m3SpecUrl,
      description: ColorThemeComponentPage.meta.description,
      notes: _notes,
      pendingVariants: _pending,
      variantsSection: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          ComponentSection(
            title: 'Theme builder',
            subtitle: 'Only primary and secondary are required. All other roles are generated.',
            child: _buildBuilderPanel(context),
          ),
          const SizedBox(height: 24),
          ComponentSection(
            title: 'Generated palette',
            subtitle: 'Full M3 color roles for the current brightness.',
            child: Theme(
              data: Theme.of(context).copyWith(colorScheme: scheme),
              child: ColorRoleSwatchGrid(scheme: scheme),
            ),
          ),
          const SizedBox(height: 24),
          ComponentSection(
            title: 'Component preview',
            subtitle: 'Sample widgets using the generated theme.',
            child: Theme(
              data: Theme.of(context).copyWith(
                colorScheme: scheme,
                brightness: _brightness,
              ),
              child: _ComponentPreview(scheme: scheme),
            ),
          ),
          const SizedBox(height: 24),
          ComponentSection(
            title: 'Export',
            subtitle: 'Copy generated Dart for app theme setup.',
            child: _ExportPanel(snippet: snippet),
          ),
        ],
      ),
    );
  }

  Widget _buildBuilderPanel(BuildContext context) {
    final theme = AppThemeScope.of(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Primary', style: Theme.of(context).textTheme.labelLarge),
                  const SizedBox(height: 8),
                  M3ColorPicker(
                    compact: true,
                    value: theme.primary,
                    onChanged: theme.setPrimary,
                  ),
                ],
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Secondary', style: Theme.of(context).textTheme.labelLarge),
                  const SizedBox(height: 8),
                  M3ColorPicker(
                    compact: true,
                    value: theme.secondary,
                    onChanged: theme.setSecondary,
                  ),
                ],
              ),
            ),
          ],
        ),
        const SizedBox(height: 20),
        SegmentedButton<Brightness>(
          segments: const [
            ButtonSegment(
              value: Brightness.light,
              label: Text('Light'),
              icon: Icon(Icons.light_mode_outlined),
            ),
            ButtonSegment(
              value: Brightness.dark,
              label: Text('Dark'),
              icon: Icon(Icons.dark_mode_outlined),
            ),
          ],
          selected: {_brightness},
          onSelectionChanged: (value) {
            setState(() => _brightness = value.first);
          },
        ),
      ],
    );
  }
}

class _ComponentPreview extends StatelessWidget {
  const _ComponentPreview({required this.scheme});

  final ColorScheme scheme;

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: scheme.surface,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text('Preview on surface', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                FilledButton(
                  onPressed: () {},
                  style: KpiButtonStyles.labelStyle(context, KpiButtonSize.s40),
                  child: const Text('Filled'),
                ),
                OutlinedButton(
                  onPressed: () {},
                  style: KpiButtonStyles.labelStyle(context, KpiButtonSize.s40),
                  child: const Text('Outlined'),
                ),
                TextButton(
                  onPressed: () {},
                  style: KpiButtonStyles.labelStyle(context, KpiButtonSize.s40),
                  child: const Text('Text'),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                FilterChip(
                  label: const Text('Filter'),
                  selected: true,
                  onSelected: (_) {},
                ),
                ActionChip(
                  label: const Text('Assist'),
                  onPressed: () {},
                ),
                FilterChip.elevated(
                  label: const Text('Elevated'),
                  selected: false,
                  onSelected: (_) {},
                ),
              ],
            ),
            const SizedBox(height: 12),
            KpiTextField(
              label: 'Text field',
              hintText: 'Hint',
              showHelperText: false,
            ),
          ],
        ),
      ),
    );
  }
}

class _ExportPanel extends StatelessWidget {
  const _ExportPanel({required this.snippet});

  final String snippet;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        DecoratedBox(
          decoration: BoxDecoration(
            border: Border.all(color: Theme.of(context).colorScheme.outlineVariant),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Padding(
            padding: const EdgeInsets.all(12),
            child: SelectableText(
              snippet,
              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                fontFamily: 'monospace',
              ),
            ),
          ),
        ),
        const SizedBox(height: 12),
        Align(
          alignment: Alignment.centerLeft,
          child: FilledButton.icon(
            onPressed: () {
              Clipboard.setData(ClipboardData(text: snippet));
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Theme snippet copied')),
              );
            },
            style: KpiButtonStyles.labelStyle(context, KpiButtonSize.s40),
            icon: Icon(Icons.copy_outlined, size: KpiButtonSize.s40.iconSize),
            label: const Text('Copy snippet'),
          ),
        ),
      ],
    );
  }
}
